thestk/stk

src/Makefile.in

This should have been part of #27, sorry for not noticing before.

Fix install target for new soname scheme

---

configure.ac
doc/doxygen/compile.txt
src/RtMidi.cpp

Fix capitalization of CoreMIDI framework to fix build on Macs with
case-sensitive filesystems.

Fix build on case-sensitive OS X

---

src/Guitar.cpp
src/Mandolin.cpp
src/Resonate.cpp

Most error messages go to oStream_.  Two in guitar.cpp don't conform.

redirect non-conforming writes to cerr to oStream_

---

src/Skini.cpp

Added a separate index for accessing tokens leaving the original index for values to work as it always does.  Code now correctly parses SKINI text for midi extension commands as well as basic commands.

#63: add separate index for tokens in parseString

---

src/Makefile.in

This PR changes the Makefile to use `cp -R` instead of `cp -r`. According to the `cp(1)` manpage on macOS, the `-r` option is historic its use is strongly discouraged.

Use cp -R instead of cp -r

---

INSTALL.md
iOS/README-iOS.md

This PR changes change "Cocoapods" to "CocoaPods" to match their preferred capitalization, and changes "http://cocoapods.org/" to "https://cocoapods.org" because their web server now redirects http traffic to https.

Use intercaps for CocoaPods and use https for web site

---

README.md

i added a space, from "##Contents" to  "## Contents", so that the formatting in Markdown is right

 fix subtitle format in README.md 

---

projects/demo/Makefile.in
projects/effects/Makefile.in
projects/eguitar/Makefile.in
projects/examples/Makefile.in
projects/examples/libMakefile.in
projects/ragamatic/Makefile.in
src/Makefile.in

Hi, I'm the maintainer of [stk in MacPorts](https://ports.macports.org/port/stk). I know the long-term goal may be to replace the stk build system with something new, possibly based on cmake, but until then I'd like to contribute some small incremental improvements to the existing build system, some of which I've already been using in MacPorts.
This first change lets the build system honor any LDFLAGS the user set when running ./configure. For example, this now works:
```
$ LDFLAGS=-Wl,-headerpad_max_install_names ./configure --enable-shared
$ make
```

Use any LDFLAGS set when running ./configure

---

src/Makefile.in

Autoconf configure scripts allow the user to specify alternate directories for exec_prefix, bindir, includedir, and libdir (see ./configure --help). Now, they are honored by the Makefile.
For example, here's how --libdir was mishandled by the build system before:
```
$ autoreconf
$ make clean
$ rm -rf destroot
$ ./configure --enable-shared --libdir=/usr/local/other
$ make install -j8 DESTDIR=$(PWD)/destroot
$ find destroot -name '*lib*'
destroot/usr/local/usr/local/other/libstk-4.6.1.dylib
destroot/usr/local/usr/local/other/libstk.dylib
```
Here's how it works after my change:
```
$ autoreconf
$ make clean
$ rm -rf destroot
$ ./configure --enable-shared --libdir=/usr/local/other
$ make install -j8 DESTDIR=$(PWD)/destroot
$ find destroot -name '*lib*' …
```

Support exec_prefix, bindir, includedir, libdir

---

include/Stk.h

This commit changes the `StkError` class so that it inherits from `std::exceptiion` class and implements `what()` method. It does not alter the current functionality of `StkError` class, exceptions of this class may be caught the same way as before. The commit allows for additional error checking by catching `std::exception` objects.
From C++ FAQ, Q17.12:
> If possible, you should throw instances of classes that derive (ultimately) from the std::exception class. By making your exception class inherit (ultimately) from the standard exception base-class, you are making life easier for your users (they have the option of catching most things via std::exception), plus you are probably providing them with more information (such as the fact that your particular exception might be a refinement …

Make StkError inherit from std::exception

---

include/Stk.h
src/Stk.cpp

Adds new constructor to `StkFrames` class that takes a pointer to an existing `StkFloat` buffer and wraps it into the `StkFrames` object. This is useful in frameworks that provide a buffer that needs to be filled with samples. Wrapping the buffer pointer in `StkFrames` class allows sending the buffer directly into `Stk` objects, without need for data copying. A single `tick` invocation is needed to fill the buffer instead of calling `tick` for each sample.
For example, the callback function in `crtsine.cpp` may be written as:
```
int tick( void *outputBuffer, void *inputBuffer, unsigned int nBufferFrames,
double streamTime, RtAudioStreamStatus status, void *dataPointer )
{
SineWave *sine = (SineWave *) dataPointer;
register StkFloat *samples = (StkFloat *) outputBuffer;
#if 1 // new …
```

Add StkFrames constructor that wraps pointer to existing buffer

---

src/Makefile.in
src/Stk.cpp

Makefile.in in src dir did not include TapDelay.cpp, so that file was not compiled into the static library when configure/make was used.

Add missing TapDelay to src/Makefile

---

include/Stk.h

This modification allows for creating classes that inherit from `StkFrames`.
In `StkFrames` class, `private` members were changed to `protected`. The following methods were made virtual: `~StkFrames`, `operator=` and `resize` (both versions). These method allocate/free memory for the data pointer, so they have to be virtual.
An example usage is wrapping a pointer to buffer provided in a callback function into a custom class derived from `StkFrames`. Such a class may be passed to STK functions as an argument of `StkFrames`, using polymorphism.
The attached example is `crtsine.cpp` project from STK, reworked using a custom wrapper.
[crtsine.cpp.txt](https://github.com/thestk/stk/files/6190300/crtsine.cpp.txt)

Allow deriving classes from StkFrames

---

include/LentPitShift.h

This PR fixes an out-of-bounds read in `process` method in `LentPitShift` class.
In this loop:
```
for ( delay_=1; delay_<=tMax_; delay_++ ) {
```
the following condition is checked:
```
if ( dpt[delay_-1]-dpt[delay_-2] < 0 && dpt[delay_]-dpt[delay_-1] > 0 ) {
```
For `delay_ == 1`, out-of-bounds read `dpt[-1]` is attempted.
This produces an undefined behaviour. In normal cases, the code works, But if the code is compiled as a library and used in another environment, a crash may occur and it is difficult to debug (took me about an hour to find the cause).
BTW, this operation:
```
dpt[delay_] = dt[delay_] * delay_ / cumDt[delay_];
```
produces a `NaN` result if `dpt[delay_]` and `cumDt[delay_]` are both zero (which may happen at the beginning of processing). This also produces an undefined …

Fix out-of-bounds read in LentPitShift

---

configure.ac

Just like on Linux where one sets a shared library's soname, one should set a macOS dylib's install_name, but unlike on Linux, on macOS the install_name should be the absolute path where the library will be installed.
Fixes #40
```
$ autoreconf
$ make clean
$ ./configure --prefix=/opt/stk --enable-shared
$ make -j8
$ otool -L src/libstk-4.6.1.dylib | head -n 2
src/libstk-4.6.1.dylib:
libstk-4.6.1.dylib (compatibility version 0.0.0, current version 0.0.0)
```
```
$ autoreconf
$ make clean
$ ./configure --prefix=/opt/stk --enable-shared
$ make -j8
$ otool -L src/libstk-4.6.1.dylib | head -n 2
src/libstk-4.6.1.dylib:
/opt/stk/lib/libstk-4.6.1.dylib (compatibility version 0.0.0, current version 0.0.0)
```

Set the install_name for the macOS dylib

---

configure.ac
include/Stk.h

Previously, there was no `--with-pulse` option in `configure` and if it was the only audio backend built, pthread support would break.

configure: fix build for --with-pulse

---

include/BiQuad.h
src/BiQuad.cpp

This branch adds functions into biquad that set the coefficients for lowpass, highpass, bandpass, bandreject and allpass filters. Each function accepts parameters for frequency and Q-factor. 
Since the formulae (taken from Udo Zölzer's DAFX) all involve calculating a set of intermediate values that are the same across the board, these are handled in an additional helper function called setCommonFilterValues. This function and the intermediate values are protected.  setCommonFilterValues also sets both the feedback coefficients, since these are also the same across the board.  Finally, the function also handles the debug check to ensure that frequency and Q parameters are both > 0. 
Since these functions modify all filter coefficients, calling setResonance or setNotch after them could …

add support for different filter types in biquad

---

CMakeLists.txt

I was unable to build until I explicitly forced c++11 standard, I was running clion and on OSX (so building with XCode 12.4)
here's some typical errors I encountered there was one other similar error on the main library
/Volumes/EXSSD/DEVELOPMENT/MAPLEPOST/stk/./include/RtMidi.h:137:19: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
RtMidi(RtMidi&& other) noexcept;
^
/Volumes/EXSSD/DEVELOPMENT/MAPLEPOST/stk/./include/RtMidi.h:137:28: error: expected ';' at end of declaration list
RtMidi(RtMidi&& other) noexcept;
^
;

simple fix to force c++11 standard

---

projects/demo/demo.vcxproj
projects/demo/demo.vcxproj.filters

The demo project definition on windows was outdated, causing it to not build properly.
The fix was to add the two missing cpp file to the project definition (Iir.cpp and Recorder.cpp) as well as define `_USE_MATH_DEFINES` to allow the compiler to use `M_SQRT1_2`.
This change also fix a compiler warning caused by a mismatch between the target name, which was `demo.exe` and the linker's output file which is stk-demo.exe.

Fix demo project on Windows

---

src/ModalBar.cpp

In ModalBar.cpp the control messages for 'Stick direct mix' and 'Vibrato amplitude' have been mixed up. This also concerns some documentation but the description on https://ccrma.stanford.edu/software/stk/classstk_1_1ModalBar.html, which is generated from the source, is correct. The following changes make modalbar control changes correspond to that documentation.
This is obviously disruptive downstream since existing code using 'Vibrato gain' or 'Stick mix' would have had to bee sending the wrong signal, as is the case in lmms. 
Fixes https://github.com/thestk/stk/issues/143

Fix mixed up control messages
